apiVersion: apps/v1
kind: Deployment
metadata:
  name: ingredient-service
spec:
  selector:
    matchLabels:
      app: ingredient-service
  template:
    metadata:
      labels:
        app: ingredient-service
    spec:
      containers:
        - image: ingredient-service:ingredient
          name: ingredient-service
          env:
            - name: DATABASE_HOST
              value: mysql
            - name: DATABASE_PORT
              value: "3306"
            - name: DATABASE_USER
              value: root
            - name: DATABASE_PASSWORD
              value: superuser
          ports:
            - containerPort: 8081

---
apiVersion: v1
kind: Service
metadata:
  name: ingredient-service
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081  # Opcjonalnie: możesz określić konkretny port NodePort, w przeciwnym razie zostanie on przydzielony automatycznie
  selector:
    app: ingredient-service
